files:  
  ignore:
    - 'src/dev/scss/**/*.scss'
rules: 
  property-sort-order:
    - 0
  indentation:
    - 0
  class-name-format:
    - 0
  empty-line-between-blocks:
    - 0
  leading-zero:
    - 0
  force-pseudo-nesting:
    - 0
  force-element-nesting:
    - 0
  single-line-per-selector:
    - 0
  empty-rules:
    - 0